export default [
    {
        id: '81010A1741B2',
        link: 'https://katepavlovich.github.io/match-match-game1',
        name: 'Match-match Game',
        src: 'https://github.com/KatePavlovich/KatePavlovich.github.io/blob/master/portfolio/img/screenshot1-match-game.jpg?raw=true',
        width: '600',
        height: '423',
        technologies: ['OOP', 'DOM', 'DOM Events', 'template literals', 'ES6', 'setTimeout'],
    },
    {
        id: '945034B249C7',
        link: 'https://katepavlovich.github.io/game.html',
        name: 'Runner Game',
        src: 'https://github.com/KatePavlovich/KatePavlovich.github.io/blob/master/portfolio/img/screenshot3.jpg?raw=true',
        width: '600',
        height: '423',
        technologies: ['OOP', 'canvas', 'IIFE', 'Module Pattern', 'requestAnimationFrame', 'keyboard events'],
    },
    {
        id: '335C98083D98',
        link: 'https://melcom.by/',
        name: 'Melcom.by',
        src: 'https://github.com/KatePavlovich/KatePavlovich.github.io/blob/master/portfolio/img/screenshot1-melc.jpg?raw=true',
        width: '600',
        height: '423',
        technologies: ['cms Wordpress', 'project design', 'forms', 'maps','SSL', 'setting hosting and domain'],
    },
    {
        id: '64D58674022E',
        link: 'https://codepen.io/asylumhere/full/VdGyQM/',
        name: 'Quotes App',
        src: 'https://github.com/KatePavlovich/KatePavlovich.github.io/blob/master/portfolio/img/1.jpg?raw=true',
        width: '600',
        height: '390',
        technologies: ['jQuery', 'Bootstrap', 'Rest Api'],
    },
    {
        id: '3172E9525F35',
        link: 'https://codepen.io/asylumhere/full/deLVZq/',
        name: 'Weather App',
        src: 'https://github.com/KatePavlovich/KatePavlovich.github.io/blob/master/portfolio/img/weaterApp.jpg?raw=true',
        width: '600',
        height: '390',
        technologies: ['jQuery', 'Bootstrap', 'Rest Api', 'geolocation'],
    },
    {
        id: '59F5863477G8',
        link: 'https://codepen.io/asylumhere/full/Kejxxw/',
        name: 'Calculator on React',
        src: 'https://github.com/KatePavlovich/rsschool-codejam1-cv/blob/gh-pages/img/calculator.jpg?raw=true',
        width: '780',
        height: '665',
        technologies: ['React', 'ES6', 'grid css'],
    },

]